version: 2

models:
     


  - name: reporting_table
    description: final weather table for dashboard purposes.
    columns:
      - name: driver_id 
        description: "The unique identifier for each driver in the refined dataset."
      