-- Create the production role
USE ROLE TRAINING_ROLE;
CREATE ROLE IF NOT EXISTS DBT_PROD_ROLE;

-- Grant permissions to build objects in the layered schemas, and to create new schemas
USE ROLE TRAINING_ROLE; -- Or another role with ownership
GRANT USAGE ON DATABASE F1_DB TO ROLE DBT_PROD_ROLE;
GRANT USAGE ON WAREHOUSE F1 TO ROLE DBT_PROD_ROLE;
GRANT CREATE SCHEMA ON DATABASE F1_DB TO ROLE DBT_PROD_ROLE;


-- Grant permission to read from any necessary source schemas

GRANT USAGE ON SCHEMA F1_DB.RAW TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA F1_DB.RAW TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA F1_DB.RAW TO ROLE DBT_PROD_ROLE;

GRANT USAGE ON SCHEMA F1_DB.REFINEMENT TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA F1_DB.REFINEMENT TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA F1_DB.REFINEMENT TO ROLE DBT_PROD_ROLE;

-- Grant permission to modify and create objects/schemas from the production schema
GRANT USAGE ON SCHEMA F1_DB.DBT_PROD TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA F1_DB.DBT_PROD TO ROLE DBT_PROD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA F1_DB.DBT_PROD TO ROLE DBT_PROD_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA F1_DB.DBT_PROD TO ROLE DBT_PROD_ROLE;
GRANT CREATE TABLE ON SCHEMA F1_DB.DBT_PROD TO ROLE DBT_PROD_ROLE;
GRANT CREATE STAGE ON SCHEMA F1_DB.DBT_PROD TO ROLE DBT_PROD_ROLE;
GRANT USAGE ON SCHEMA F1_DB.DBT_PROD TO ROLE DBT_PROD_ROLE;


--Security considerations:
-- Assign this new role to the users who are authorized to deploy
GRANT ROLE DBT_PROD_ROLE TO USER eagle;
GRANT ROLE DBT_PROD_ROLE TO USER cobra;